# Generated by Django 4.2.30 on 2026-08-31 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=50)),
                ('zone', models.CharField(choices=[('group', 'Group study (green, levels 2–3)'), ('quiet', 'Quiet study (amber, levels 1, 4–7)'), ('silent', 'Silent study (red, levels 8–12)')], max_length=6)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('end_time', models.DateTimeField(editable=False, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verify_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
