# Generated by Django 4.2.30 on 2026-10-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["is_verified", "end_time"], name="board_live_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["email", "end_time"], name="board_email_idx"),
        ),
    ]
